function [ model ] = genetic_executemetamerged( ...
    aa_mode, corpus_name, selection, description, genetic_model )
%genetic_executemetamerged run a genetic search for the meta merged
%algorithm

nested_genetic = @(modelvector)...
    genetic_optimizationevaluator_metamerged( ...
        modelvector,corpus_name,aa_mode,selection);

model = genetic_optimizeparams_metamerged( ...
    nested_genetic, ...
    description, ...
    genetic_model  );

model.description = description;

end

